# Generated by Django 4.2.23 on 2025-08-12 19:53

from django.db import migrations, models
import video.models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='videoframe',
            name='video_and_index_unique',
        ),
        migrations.AddField(
            model_name='video',
            name='file',
            field=models.FileField(blank=True, help_text='Generated from compiling frames', upload_to=video.models.video_file_path),
        ),
        migrations.AddField(
            model_name='videoframe',
            name='ordering',
            field=models.FloatField(default=0, help_text='Ordering from the front end'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videoframe',
            name='png',
            field=models.FileField(blank=True, help_text='Generated from svg', upload_to=video.models.video_frame_png_path),
        ),
        migrations.AlterField(
            model_name='videoframe',
            name='index',
            field=models.PositiveIntegerField(blank=True, help_text='Generated by back end after receiving all frames', null=True),
        ),
    ]
