# Generated by Django 4.2.23 on 2025-08-13 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_remove_videoframe_video_and_index_unique_video_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videoframe',
            name='svg_content',
        ),
    ]
