# Generated by Django 4.2.23 on 2025-08-13 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_remove_videoframe_svg_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='file_framerate',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
