SECRET_KEY: "<SECRET_KEY>"
BABEL_DEFAULT_LOCALE: "<DEFAULT_LANGUAGE>"
APPLICATION_ROOT: "<APPLICATION_ROOT>/"
OAUTH_MWURI: "https://meta.wikimedia.org/w/index.php"
CONSUMER_KEY: "<CONSUMER_KEY>"
CONSUMER_SECRET: "<CONSUMER_SECRET>"