# Generated by Django 4.2.23 on 2025-08-13 19:26

from django.db import migrations, models
import django.db.models.deletion
import video.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(blank=True, help_text='Generated from compiling frames', upload_to=video.models.video_file_path)),
                ('file_framerate', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VideoFrame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('ordering', models.FloatField(help_text='Ordering from the front end')),
                ('index', models.PositiveIntegerField(blank=True, help_text='Generated by back end after receiving all frames', null=True)),
                ('png', models.FileField(blank=True, help_text='Generated from svg', upload_to=video.models.video_frame_png_path)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frames', to='video.video')),
            ],
        ),
    ]
