name: Toolforge Deploy
on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    name: Deploy to Toolforge
    runs-on: ubuntu-latest

    steps:
      - name: Configure SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}

      - name: Run deployment commands
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ vars.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ vars.SSH_PORT }}
          request_pty: true
          script: |
            set -xe
            become infographics toolforge build clean -y
            become infographics toolforge build start https://github.com/wikimediabrasil/wiki_infographics
            become infographics toolforge jobs run --image tool-infographics/tool-infographics:latest --command "migrate" --no-filelog --wait --mount=all migrate
            become infographics toolforge webservice stop
            become infographics toolforge webservice buildservice start --mount all
            become infographics toolforge webservice buildservice status
